version: '3.1'
services:
  springboot:
    image: swaroopchalla/maven-web-application:11 .
    restart: always
    ports:
    - 9090:8080
    networks:
    - mavenappbridge
networks:
  mavenappbridge:
